### ISSUE TITLE
 java.lang.IllegalArgumentException: Invalid null NBT value with key normal

### ISSUE THREAD

**Issue by Yourname942** [fredtargaryen/Rocket-Squids#17] opened 2021-01-05 22:38 UTC
Minecraft 1.16.4
Forge 35.1.29
Rocket Squids 1.4.0
Just Enough Items 7.6.1.65

Steps to reproduce:
1) launch Minecraft
2) launch the server
3) Give yourself the Squeleporter via JEI
4) look at a rocketsquid
5) right click the squeleporter on a  rocket squid (be pretty close to it) and then crash

latest log:
https://gist.github.com/Yourname942/3826765b3991a39d2ce54c7f6fb66da2

**Comment by fredtargaryen** [comment] 2021-01-11 19:59
Hi! I think I fixed this in [version 1.4.1](https://www.curseforge.com/minecraft/mc-mods/rocket-squids/files/3163635). Please could you try that and see if that has fixed things?

**Comment by fredtargaryen** [comment] 2021-01-23 21:56
Hi, have you had a chance to confirm whether or not the issue is sorted? I'm going to close this in a few days if I don't hear back.

**Comment by fredtargaryen** [comment] 2021-01-30 08:54
Closed due to inactivity.

**Closed as completed by fredtargaryen** 2021-01-30 08:54 UTC
Labels: bug
